version: '3'

services:
  app:
    container_name: app
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db    
    networks: 
      - node-network

  db:
    container_name: db
    image: mysql:5.7               
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/migrations:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network      

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge  